package com.inventory.system.common.entity;

public enum FinancialEventType {
    GOODS_RECEIPT,
    STOCK_ADJUSTMENT,
    WAREHOUSE_TRANSFER,
    POS_SALE,
    SALES_REFUND,
    SUPPLIER_RETURN,
    DAMAGE_WRITE_OFF,
    SALES_ORDER_DELIVERY,
    SALES_ORDER_PARTIAL_DELIVERY,
    SALES_ORDER_RETURN,
    COURIER_FEE,
    COD_COLLECTION_FEE,
    COURIER_SETTLEMENT,
    TAX_REMITTANCE,
    MANUAL_JOURNAL
}
