ALTER TABLE sales_order_items
    ADD COLUMN IF NOT EXISTS fulfilled_quantity NUMERIC(19,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS returned_quantity  NUMERIC(19,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cancelled_quantity NUMERIC(19,6) NOT NULL DEFAULT 0;
